# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    assignees:
      - "@me"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    reviewers:
      - "@me"
    labels:
      - "dependencies"
      - "python"
    # Group updates for better PR management
    groups:
      # Group major version updates together
      major-updates:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-major"
      # Group minor and patch updates by category
      testing-dependencies:
        patterns:
          - "pytest*"
          - "coverage*"
          - "factory-boy"
          - "faker"
          - "responses"
          - "moto"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
      linting-dependencies:
        patterns:
          - "black"
          - "isort"
          - "flake8*"
          - "mypy"
          - "bandit"
          - "safety"
          - "autoflake"
          - "pyupgrade"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
      aws-dependencies:
        patterns:
          - "boto3"
          - "botocore"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    # Allow automatic merging for patch updates to known safe packages
    allow:
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
      - dependency-type: "indirect"
        update-type: "version-update:semver-patch"
    # Ignore specific dependencies that need manual review
    ignore:
      - dependency-name: "requests"
        update-types: ["version-update:semver-major"]
      - dependency-name: "boto3"
        update-types: ["version-update:semver-major"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    assignees:
      - "@me"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "@me"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  # Docker dependencies (if you add Dockerfile later)
  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #     day: "monday"
  #     time: "06:00"
  #     timezone: "UTC"
  #   open-pull-requests-limit: 3
  #   assignees:
  #     - "@me"
  #   commit-message:
  #     prefix: "docker"
  #     include: "scope"
  #   reviewers:
  #     - "@me"
  #   labels:
  #     - "dependencies"
  #     - "docker"